//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentasCal.Datos.Recursos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CamposConstantes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CamposConstantes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VentasCal.Datos.Recursos.CamposConstantes", typeof(CamposConstantes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApellidoMaterno.
        /// </summary>
        public static string CC_ApellidoMaterno {
            get {
                return ResourceManager.GetString("CC_ApellidoMaterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApellidoPaterno.
        /// </summary>
        public static string CC_ApellidoPaterno {
            get {
                return ResourceManager.GetString("CC_ApellidoPaterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string CC_Area {
            get {
                return ResourceManager.GetString("CC_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articulo.
        /// </summary>
        public static string CC_Articulo {
            get {
                return ResourceManager.GetString("CC_Articulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad.
        /// </summary>
        public static string CC_Cantidad {
            get {
                return ResourceManager.GetString("CC_Cantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClaveArea.
        /// </summary>
        public static string CC_ClaveArea {
            get {
                return ResourceManager.GetString("CC_ClaveArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClaveArticulo.
        /// </summary>
        public static string CC_ClaveArticulo {
            get {
                return ResourceManager.GetString("CC_ClaveArticulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClaveEntidad.
        /// </summary>
        public static string CC_ClaveEntidad {
            get {
                return ResourceManager.GetString("CC_ClaveEntidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClaveEstado.
        /// </summary>
        public static string CC_ClaveEstado {
            get {
                return ResourceManager.GetString("CC_ClaveEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClaveProveedor.
        /// </summary>
        public static string CC_ClaveProveedor {
            get {
                return ResourceManager.GetString("CC_ClaveProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClaveResponsable.
        /// </summary>
        public static string CC_ClaveResponsable {
            get {
                return ResourceManager.GetString("CC_ClaveResponsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente.
        /// </summary>
        public static string CC_Cliente {
            get {
                return ResourceManager.GetString("CC_Cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codigo.
        /// </summary>
        public static string CC_Codigo {
            get {
                return ResourceManager.GetString("CC_Codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comentarios.
        /// </summary>
        public static string CC_Comentarios {
            get {
                return ResourceManager.GetString("CC_Comentarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacto.
        /// </summary>
        public static string CC_Contacto {
            get {
                return ResourceManager.GetString("CC_Contacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrasena.
        /// </summary>
        public static string CC_Contrasena {
            get {
                return ResourceManager.GetString("CC_Contrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CorreoElectronico.
        /// </summary>
        public static string CC_CorreoElectronico {
            get {
                return ResourceManager.GetString("CC_CorreoElectronico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripcion.
        /// </summary>
        public static string CC_Descripcion {
            get {
                return ResourceManager.GetString("CC_Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direccion.
        /// </summary>
        public static string CC_Direccion {
            get {
                return ResourceManager.GetString("CC_Direccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa.
        /// </summary>
        public static string CC_Empresa {
            get {
                return ResourceManager.GetString("CC_Empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FechaCambio.
        /// </summary>
        public static string CC_FechaCambio {
            get {
                return ResourceManager.GetString("CC_FechaCambio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FechaCompra.
        /// </summary>
        public static string CC_FechaCompra {
            get {
                return ResourceManager.GetString("CC_FechaCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdUsuario.
        /// </summary>
        public static string CC_IdUsuario {
            get {
                return ResourceManager.GetString("CC_IdUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importe.
        /// </summary>
        public static string CC_Importe {
            get {
                return ResourceManager.GetString("CC_Importe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marca.
        /// </summary>
        public static string CC_Marca {
            get {
                return ResourceManager.GetString("CC_Marca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificaciones.
        /// </summary>
        public static string CC_Modificaciones {
            get {
                return ResourceManager.GetString("CC_Modificaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string CC_Nombre {
            get {
                return ResourceManager.GetString("CC_Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El objeto es de solo lectura..
        /// </summary>
        public static string CC_ObjetoLectura {
            get {
                return ResourceManager.GetString("CC_ObjetoLectura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrecioReal.
        /// </summary>
        public static string CC_PrecioReal {
            get {
                return ResourceManager.GetString("CC_PrecioReal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrecioUnitario.
        /// </summary>
        public static string CC_PrecioUnitario {
            get {
                return ResourceManager.GetString("CC_PrecioUnitario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsable.
        /// </summary>
        public static string CC_Responsable {
            get {
                return ResourceManager.GetString("CC_Responsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefono.
        /// </summary>
        public static string CC_Telefono {
            get {
                return ResourceManager.GetString("CC_Telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TipoUsuario.
        /// </summary>
        public static string CC_TipoUsuario {
            get {
                return ResourceManager.GetString("CC_TipoUsuario", resourceCulture);
            }
        }
    }
}
