//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentasCal.Datos.Recursos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mensajes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensajes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VentasCal.Datos.Recursos.Mensajes", typeof(Mensajes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        public static string C_Activo {
            get {
                return ResourceManager.GetString("C_Activo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrador.
        /// </summary>
        public static string C_Administrador {
            get {
                return ResourceManager.GetString("C_Administrador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha agregado una nueva area.
        /// </summary>
        public static string C_AgregarArea {
            get {
                return ResourceManager.GetString("C_AgregarArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha agregado un nuevo articulo.
        /// </summary>
        public static string C_AgregarArticulo {
            get {
                return ResourceManager.GetString("C_AgregarArticulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha agregado un nuevo bien.
        /// </summary>
        public static string C_AgregarBien {
            get {
                return ResourceManager.GetString("C_AgregarBien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AgregarModificar.
        /// </summary>
        public static string C_AgregarModificar {
            get {
                return ResourceManager.GetString("C_AgregarModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha agregado un nuevo proveedor..
        /// </summary>
        public static string C_AgregarProveedor {
            get {
                return ResourceManager.GetString("C_AgregarProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha agregado un nuevo responsable.
        /// </summary>
        public static string C_AgregarResponsable {
            get {
                return ResourceManager.GetString("C_AgregarResponsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClaveEntidad.
        /// </summary>
        public static string C_ClaveEntidad {
            get {
                return ResourceManager.GetString("C_ClaveEntidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripcion.
        /// </summary>
        public static string C_Descripcion {
            get {
                return ResourceManager.GetString("C_Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string C_Editar {
            get {
                return ResourceManager.GetString("C_Editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha modificado la area.
        /// </summary>
        public static string C_EditarArea {
            get {
                return ResourceManager.GetString("C_EditarArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha modificado el articulo.
        /// </summary>
        public static string C_EditarArticulo {
            get {
                return ResourceManager.GetString("C_EditarArticulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha modificado el bien.
        /// </summary>
        public static string C_EditarBien {
            get {
                return ResourceManager.GetString("C_EditarBien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha modificado el proveedor.
        /// </summary>
        public static string C_EditarProveedor {
            get {
                return ResourceManager.GetString("C_EditarProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha modificado el responsable.
        /// </summary>
        public static string C_EditarResponsable {
            get {
                return ResourceManager.GetString("C_EditarResponsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string C_Estado {
            get {
                return ResourceManager.GetString("C_Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FechaCambio.
        /// </summary>
        public static string C_fechaCambio {
            get {
                return ResourceManager.GetString("C_fechaCambio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folio.
        /// </summary>
        public static string C_Folio {
            get {
                return ResourceManager.GetString("C_Folio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string C_ID {
            get {
                return ResourceManager.GetString("C_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactivo.
        /// </summary>
        public static string C_Inactivo {
            get {
                return ResourceManager.GetString("C_Inactivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string C_Page {
            get {
                return ResourceManager.GetString("C_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsable.
        /// </summary>
        public static string C_Responsable {
            get {
                return ResourceManager.GetString("C_Responsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione.
        /// </summary>
        public static string C_Seleccione {
            get {
                return ResourceManager.GetString("C_Seleccione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        public static string C_Usuario {
            get {
                return ResourceManager.GetString("C_Usuario", resourceCulture);
            }
        }
    }
}
