//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentasCal.Datos.Recursos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ParametrosConstantes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ParametrosConstantes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VentasCal.Datos.Recursos.ParametrosConstantes", typeof(ParametrosConstantes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VC.
        /// </summary>
        public static string EsquemaSDI {
            get {
                return ResourceManager.GetString("EsquemaSDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @VApellidoMaterno.
        /// </summary>
        public static string PC_ApellidoMaterno {
            get {
                return ResourceManager.GetString("PC_ApellidoMaterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @VApellidoPaterno.
        /// </summary>
        public static string PC_ApellidoPaterno {
            get {
                return ResourceManager.GetString("PC_ApellidoPaterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @VArchivo.
        /// </summary>
        public static string PC_Archivo {
            get {
                return ResourceManager.GetString("PC_Archivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @VCantidad.
        /// </summary>
        public static string PC_Cantidad {
            get {
                return ResourceManager.GetString("PC_Cantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @VClaveArea.
        /// </summary>
        public static string PC_ClaveArea {
            get {
                return ResourceManager.GetString("PC_ClaveArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @VClaveArticulo.
        /// </summary>
        public static string PC_ClaveArticulo {
            get {
                return ResourceManager.GetString("PC_ClaveArticulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @VClaveEntidad.
        /// </summary>
        public static string PC_ClaveEntidad {
            get {
                return ResourceManager.GetString("PC_ClaveEntidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @VClaveEstado.
        /// </summary>
        public static string PC_ClaveEstado {
            get {
                return ResourceManager.GetString("PC_ClaveEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @VClaveProveedor.
        /// </summary>
        public static string PC_ClaveProveedor {
            get {
                return ResourceManager.GetString("PC_ClaveProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @VClaveResponsable.
        /// </summary>
        public static string PC_ClaveResponsable {
            get {
                return ResourceManager.GetString("PC_ClaveResponsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @VCliente.
        /// </summary>
        public static string PC_Cliente {
            get {
                return ResourceManager.GetString("PC_Cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @VCodigo.
        /// </summary>
        public static string PC_Codigo {
            get {
                return ResourceManager.GetString("PC_Codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @VComentarios.
        /// </summary>
        public static string PC_Comentarios {
            get {
                return ResourceManager.GetString("PC_Comentarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @VContacto.
        /// </summary>
        public static string PC_Contacto {
            get {
                return ResourceManager.GetString("PC_Contacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @VContrasena.
        /// </summary>
        public static string PC_Contrasena {
            get {
                return ResourceManager.GetString("PC_Contrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @VCorreoElectronico.
        /// </summary>
        public static string PC_CorreoElectronico {
            get {
                return ResourceManager.GetString("PC_CorreoElectronico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VentasCal.
        /// </summary>
        public static string PC_DataBase {
            get {
                return ResourceManager.GetString("PC_DataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @VDescripcion.
        /// </summary>
        public static string PC_Descripcion {
            get {
                return ResourceManager.GetString("PC_Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @VDireccion.
        /// </summary>
        public static string PC_Direccion {
            get {
                return ResourceManager.GetString("PC_Direccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @VEmpresa.
        /// </summary>
        public static string PC_Empresa {
            get {
                return ResourceManager.GetString("PC_Empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @VFechaCambio.
        /// </summary>
        public static string PC_FechaCambio {
            get {
                return ResourceManager.GetString("PC_FechaCambio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @VFechaCompra.
        /// </summary>
        public static string PC_FechaCompra {
            get {
                return ResourceManager.GetString("PC_FechaCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @VIdUsuario.
        /// </summary>
        public static string PC_IdUsuario {
            get {
                return ResourceManager.GetString("PC_IdUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @VImporte.
        /// </summary>
        public static string PC_Importe {
            get {
                return ResourceManager.GetString("PC_Importe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @VMarca.
        /// </summary>
        public static string PC_Marca {
            get {
                return ResourceManager.GetString("PC_Marca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @VNombre.
        /// </summary>
        public static string PC_Nombre {
            get {
                return ResourceManager.GetString("PC_Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @VNOPCION.
        /// </summary>
        public static string PC_NOPCION {
            get {
                return ResourceManager.GetString("PC_NOPCION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @VObservaciones.
        /// </summary>
        public static string PC_Observaciones {
            get {
                return ResourceManager.GetString("PC_Observaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @VPrecioReal.
        /// </summary>
        public static string PC_PrecioReal {
            get {
                return ResourceManager.GetString("PC_PrecioReal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @VPrecioUnitario.
        /// </summary>
        public static string PC_PrecioUnitario {
            get {
                return ResourceManager.GetString("PC_PrecioUnitario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @VTelefono.
        /// </summary>
        public static string PC_Telefono {
            get {
                return ResourceManager.GetString("PC_Telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @VTipoUsuario.
        /// </summary>
        public static string PC_TipoUsuario {
            get {
                return ResourceManager.GetString("PC_TipoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @VValidaCampo.
        /// </summary>
        public static string PC_ValidaCampo {
            get {
                return ResourceManager.GetString("PC_ValidaCampo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @VValidaMail.
        /// </summary>
        public static string PC_ValidaMail {
            get {
                return ResourceManager.GetString("PC_ValidaMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @VValidaUsuario.
        /// </summary>
        public static string PC_ValidaUsuario {
            get {
                return ResourceManager.GetString("PC_ValidaUsuario", resourceCulture);
            }
        }
    }
}
